<?php
// $Id: luceneapi.exception.inc,v 1.1.2.2 2009/07/24 01:09:22 cpliakas Exp $

/**
 * @file
 * Defines the LuceneAPI_Exception class in cases where the Zend Framework
 * componets are unavailable.  DO NOT source this file unless you are positive
 * the LuceneAPI_Exception class is unavailable.
 *
 * @ingroup luceneapi
 */

/**
 * The LuceneAPI_Exception class.
 */
class LuceneAPI_Exception extends Exception {
}
